version: '3.9'

services:
  backend:
    image: amedicedev/api-core:alpha-0.2
    command: gunicorn amedice.wsgi:application --bind 0.0.0.0:8000 --workers=2
    restart: always
    volumes:
      - ./config.yaml:/app/etc/config/config.yaml
      - staticfiles_vol:/app/staticfiles
      - mediafiles_vol:/app/mediafiles
    expose:
      - 8000
    environment:
      - CONFIG_NAME=/app/etc/config/config.yaml
      - SECRETS_DIR=/app/etc/secrets/
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - pg_data_vol:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    restart: always

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - staticfiles_vol:/app/staticfiles
      - mediafiles_vol:/app/mediafiles
    ports:
      - "80:80"
    depends_on:
      - backend

  frontend:
    image: amedicedev/client:latest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./.env.frontend

volumes:
  pg_data_vol:
    external: True
  staticfiles_vol:
    external: True
  mediafiles_vol:
    external: True